### PR TITLE
Minio upload api

### PR DESCRIPTION
**Pull request by sahithyaravi**
#### What does this PR implement/fix? Explain your changes.
- Modify the data upload API to support upload of parquet files. 
- Modify the data upload API to perform conversions using python scripts and upload both ARFF and parquet files to minio server.
-  The existing functionality of ARFF upload should not be affected.( except python API no other client API's dowload form minio yet)

**Implementation:**

**Upload arguments:**
- In the POST request,  ARFF file can be provided as usual using the field _**dataset**_ 
- parquet file can be provided using the new field _**dataset_pq**_
- We allow upload of either pq or ARFF (not both).

**CASE 1: ONLY ARFF is provided**
-  When ARFF is uploaded, we store it in the DATA folder(as always)
- After dataset id is generated, we convert ARFF to pq using a python script and then upload both pq and ARFF to minio server.
- Conversion and upload done in the same script`minio_upload_arff_to_pq.py`
Corresponding lines of code: https://github.com/openml/OpenML/blob/0903a01722a553682f81958a38f29cc9d7d9ad19/openml_OS/models/api/v1/Api_data.php#L1259

**CASE 2: Only pq is provided** 
- When pq is provided,  we convert it to ARFF  by invoking ` minio_convert_pq_to_arff.py`  (https://github.com/openml/OpenML/blob/0903a01722a553682f81958a38f29cc9d7d9ad19/openml_OS/models/api/v1/Api_data.php#L1102)
- We perform ARFF checks as usual and store the converted ARFF locally (in the data folder).  After this, dataset id is generated as usual. (https://github.com/openml/OpenML/blob/0903a01722a553682f81958a38f29cc9d7d9ad19/openml_OS/models/api/v1/Api_data.php#L1173)
- then upload both pq and ARFF to minio using  `minio_upload.py`. (https://github.com/openml/OpenML/blob/0903a01722a553682f81958a38f29cc9d7d9ad19/openml_OS/models/api/v1/Api_data.php#L1251)

#### How should this PR be tested?
ARFF as usual using the field **dataset**
pq is provided using the field **dataset_pq**
create POST requests and check minio server.

#### Any other comments?
We need to wait to merge this, we need a test minio server.
Apologies for numerous small commits, had to do this in order to test on the test server bit by bit

### CODE REVIEW

**Comment by sahithyaravi** [comment]
In this round of changes, do we want to start bypassing the file table completely?
For example, Do we want the URL field in the dataset table to point to the local ARFF file as it does now or a minio URL containing the ARFF file? I think it should be the latter.

When we receive an ARFF file, we could just upload it to minio server directly (by bypassing the file table)
It may be better to do this as we want to move away from the file table eventually. Further, we are not going to merge this branch to master, until we test it and we are completely sure it works.

The basic idea would be:       
-  Whether the user provides ARFF or parquet, upload it to the minio server directly. This upload must happen from the API by calling a short python script.
-  File_id field is set to null ( we don’t care about the file table entry)
-  Url is set to the uploaded minio link. We could have ARFF_url and parquet_url as two fields as well. Or URL could be ARFF and parquet_url could be a new field.
-  Cron job does the conversion from ARFF to parquet or vice versa and once done it sets the appropriate URL to download the other file (parquet or arff). So the cron job has to access the db and set this field.
- The data_get API can have two fields for now. For example the url field can keep returning ARFF and the parquet_url field can return parquet.
- We throw an error for ARFF uploads with size > 1GB for example

@janvanrijn @joaquinvanschoren  Do you think we can try this out as the next step?

**Comment by janvanrijn** [comment]
> In this round of changes, do we want to start bypassing the file table completely?

Please note that the URL field in the dataset is not really used anymore, and that the Java and Python API use the file_id column from the file table. 

As such, I wouldn't be against it, but we should probably coordinate it a bit better also with @mfeurer 

Also, how do you envision the conversion if someone uploads a Parquet file (that won't be converted during the API call, but in a separate cronjob). How do you store the information on which Parquet files still need to be converted? 

> We throw an error for ARFF uploads with size > 1GB for example

Can do that, although the need is smaller when the conversion happens in the background (through a Cronjob)

**Comment by joaquinvanschoren** [comment]
> Please note that the URL field in the dataset is not really used anymore, and that the Java and Python API use the file_id column from the file table.

Really? I thought that the Python API uses the URL:
https://github.com/openml/openml-python/blob/b0765a59471b780d655143f2566785a2776f90ba/openml/datasets/functions.py#L1040

They just read the description from get_data(id) and then get the file from the URL in the description?

> As such, I wouldn't be against it, but we should probably coordinate it a bit better also with @mfeurer

Always a good idea. Also @PGijsbers can advice on this.

> Also, how do you envision the conversion if someone uploads a Parquet file (that won't be converted during the API call, but in a separate cronjob). How do you store the information on which Parquet files still need to be converted?

Good question. This needs to be stored in the database as part of the API call?

> > We throw an error for ARFF uploads with size > 1GB for example
> Can do that, although the need is smaller when the conversion happens in the background (through a Cronjob)

What was the reason again? I thought that this was for the sake of the clients, right? A 1GB ARFF file is almost imparsible by the python parser (it would take a lot of memory and be insanely slow?).

**Comment by sahithyaravi** [comment]
Also, how do you envision the conversion if someone uploads a Parquet file (that won't be converted during the API call, but in a separate cronjob). How do you store the information on which Parquet files still need to be converted?

> Good question. This needs to be stored in the database as part of the API call?
> 
> > >

Yeah it may be better if it is stored in the database in some manner and the cron job can just query the datasets with those field/fields (pq_format, arff_format) set  for example.

**Comment by mfeurer** [comment]
Sorry, I'm not sure how I can help here.

**Comment by PGijsbers** [comment]
> They just read the description from get_data(id) and then get the file from the URL in the description?

Yes, that's exactly what we do. We simply query the url specified at `<oml:url>` for obtain the ARFF file.

**Comment by sahithyaravi** [comment]
> > They just read the description from get_data(id) and then get the file from the URL in the description?
> 
> Yes, that's exactly what we do. We simply query the url specified at `<oml:url>` for obtain the ARFF file.

Thats what I thought as well, This is why we need to make sure we have the ARFF in the url field and another field parquet_url for the parquet . I think right now we return a minio_url as part of the data GET API, which python API uses to download parquet but this is just created on the fly in the get API .We can remove it and just have a parquet_url field as part of the dataset table.

**Comment by PGijsbers** [comment]
Please allow for a period where both `minio_url` and `parquet_url` are supported, so that we have some time to make the changes.

**Comment by PGijsbers** [comment]
Also don't forget to check with the R API if they use the `file_id`?

**Comment by joaquinvanschoren** [comment]
Maybe this would be a good point to create a v2 of the API, so that clients don't break. There are also a few other open issues requiring breaking changes.

IIUC, this requires that we copy api/v1 to api/v2 here, and make further changes in v2:
https://github.com/openml/OpenML/tree/develop/openml_OS/models -> models
https://github.com/openml/OpenML/tree/develop/openml_OS/views/pages -> xsd's etc

To properly redirect, I think we also need to adapt:
https://github.com/openml/OpenML/blob/develop/openml_OS/controllers/Api_new.php

The clients do need to support (or default to) v2.
Thoughts?

**Comment by mfeurer** [comment]
> The clients do need to support (or default to) v2.
Thoughts?

We would then basically change the server URL from `"https://www.openml.org/api/v1/xml"` to `"https://www.openml.org/api/v2/xml"` and that's it?

Or would there be a requirement to support both API versions?

**Comment by joaquinvanschoren** [comment]
Yes, that's it, unless you want the client to support multiple versions.
Probably you just want to switch to v2 in the next release.

**Comment by prabhant** [comment]
> Can do that, although the need is smaller when the conversion happens in the background (through a Cronjob)

I noticed that arff conversion can take a huge amount of time or fail from time to time. I'll prefer to have the same rule for test and production servers and limit the size(to 1GB) unless we have a strong reason to allow arff file larger than that.

**Comment by PGijsbers** [comment]
If there's a `v2` please document the changes from `v1` well, otherwise each programmatic interface team (Java/Python/R) needs to dredge through the code.

**Comment by sahithyaravi** [comment]
> Please allow for a period where both `minio_url` and `parquet_url` are supported, so that we have some time to make the changes.

Sure,  that wont be a problem, we can have both fields returned for a while.

**Comment by sahithyaravi** [comment]
> IUC, this requires that we copy api/v1 to api/v2 here, and make further changes in v2:
> https://github.com/openml/OpenML/tree/develop/openml_OS/models -> models
 
That is a good idea.
So we will support both v1 and v2, and client APIs will have time to transition to v2

**Comment by sahithyaravi** [comment]
@janvanrijn @joaquinvanschoren 

We are going to do these changes as part of v2 of the API.
DB changes:	

- Add a new field: parquet_url  in the dataset table, this will point to minio parquet file. 
- Add a new field:  _ex: converted_ to indicate if conversion has been performed for that dataset ID

API changes:
- Once a parquet or ARFF file is uploaded, we invoke the minio_upload script from the API to store the uploaded file on  minio server

- After upload, we can set _url_ field (if ARFF is uploaded) or _parquet_url_ field(if parquet is uploaded) - both of these could be  minio urls (not file_id based)

- Can we stop storing the ARFF on our server's file system? Or do we want to keep storing ARFFs in both the file system and minio server? If we want to continue storing ARFFs  on the server, we could still have a file_id value for these ARFFs . File ID will be NULL for parquet uploads.  
		
Cron job:	

- This python script has to first access the database and get the list of datasets which are not converted yet.
- perform the conversion
- Upload to minio
- Set the relevent URL field in the database (url field for ARFF and parquet_url field for parquet)

**Comment by janvanrijn** [comment]
Hi all,

I indeed see the need for having an API v2 here. We should aim to shut down
version 1 soon after we have version 2 stable.

Is there a way that we can prepare a v2 first without any changes to the
first version?
That way, we can make a second PR with the actual changes, and we can
actually see the diff rather than working through 135 files.
That would make it easier to review.

Best,
Jan


Op wo 2 jun. 2021 om 10:15 schreef Sahithya Ravi ***@***.***>:

**Comment by sahithyaravi** [comment]
https://github.com/openml/OpenML/pull/1107 In this PR, there are no minio changes introduced. It is just a copy of v1. If this works, we can continue to make minio changes in v2 instead of v1.

**Comment by janvanrijn** [comment]
Excellent!

Would it be an idea to include a mechanism that:
a) checks for a given api model in v2 whether it exists, and if not, uses the one from v1?
b) do the same for template files?

That way we should only add controllers / models for files that we want to change. 

(just an idea, thoughts would be great)

**Comment by sahithyaravi** [comment]
> Excellent!
> 
> Would it be an idea to include a mechanism that:
> a) checks for a given api model in v2 whether it exists, and if not, uses the one from v1?
> b) do the same for template files?

@janvanrijn  Copying v1->v2 seemed to be the easiest, but  it does result in a an extra copy of the same file
I will have to check how to do this. 

For now v2 is going to have changes in Api_data (minio upload) and may be in future flow changes so Api_flow
In other cases v2 = v1
> That way we should only add controllers / models for files that we want to change.
> 
> (just an idea, thoughts would be great)

**Comment by sahithyaravi** [comment]
@janvanrijn @joaquinvanschoren  @prabhant, Here's an outline of what has been done so far and what we still need to do to get minio and parquet support to work: 
What we have so far on minio-upload-api branch
- [x] **Upload** :  The upload API supports ARFF or parquet uploads. It uploads them to minio server instead of server file system. It adds the dataset to a data_conversion table which will be later used by a cron job to do conversions outside the API.

- [x] **Conversion**: We have a python script (to be a cron job later) which collects datasets from the data_conversion table, converts them to the needed format and uploads to minio.
- [x] **Size limit**: We have a size limit of 1GB, beyond which do not support ARFF uploads and parquet to ARFF conversions
- [x] **Initial test**: All these changes were manually tested with post requests on the test server (by checking out minio-upload-api branch).

What still needs to be done

- [ ] **Processing**: Right now, the datasets uploaded through this API will not be processed. The dataset processing needs to make two changes to support this: 

> - [ ] We want it to work based on the url(ARFF) /parquet_url(Parquet) instead of fetching the dataset from the server's file system.
> - [ ] support processing based on parquet format. (as some datasets will only have parquet no ARFF)

- [x] **Moving older datasets**: Right now, we have changes done in the upload API which handles new uploads. We need to:

> - [x] Upload all old datasets(uploaded in ARFF and based on file ID) to minio server once the minio server is ready.
> - [x] Change the url field of the dataset to be based on MINIO_URL instead of file ID (right now its based on file ID). We want it to be something like:  `MINIO_URL .'dataset'. $id . '/dataset_' . $id . '.arff';`

- [ ] **Code  quality**:  Removing some prints, format checks, reorg if needed (before merge.)

**Comment by prabhant** [comment]
The k8s server is ready and almost all active datasets are uploaded to minio on k8s in parquet format. I will be uploading other datasets timely. How are we planning to deal with preprocessing issue here?

**Pull request merged**
