### PR TITLE
trigger r package

### PR DESCRIPTION
**Pull request by giuseppec**
let's see if that works

### CODE REVIEW

**Comment by joaquinvanschoren** [comment]
This will fail because there isn't any Java code to run anymore (it was moved to a different repo).

**Comment by joaquinvanschoren** [comment]
That worked but now running into a permission problem:
```
$ bash -c 'echo $BASH_VERSION'
4.3.11(1)-release
0.01s$ ./trigger_r_package.sh
/home/travis/.travis/job_stages: line 57: ./trigger_r_package.sh: Permission denied
The command "./trigger_r_package.sh" exited with 126.
```

Can you update the permissions or should I sudo it?

**Comment by giuseppec** [comment]
Works now ;).
Do we have any other repos that could cause the R package to fail where the same script could be added?

**Comment by joaquinvanschoren** [comment]
No, only the API I believe :)

**Pull request merged**
