### PR TITLE
attempt  v2

### PR DESCRIPTION
**Pull request by sahithyaravi**
create a new version of api - v2

I have checked out this branch on the test server right now, and created a branch on openml-python to test as many API calls as possible with v2 instead of v1, 

Here is the branch on openml-python https://github.com/openml/openml-python/runs/2719068409
Some tests are failing, but they are not related to v2.

### CODE REVIEW

**Comment by janvanrijn** [comment]
I see that almost all files have changes, making it impossible to review the differences. 

Can you please turn this back, so we can review it in v1?

**Comment by sahithyaravi** [comment]
> I see that almost all files have changes, making it impossible to review the differences.

Out of 135 files almost all of the changes are additions (just a copy of V1 to v2) without any changes
The only file that has changed is **\OpenML\openml_OS\controllers\Api_new.php**

> Can you please turn this back, so we can review it in v1?

The only change here is copying of files from v1-v2 and I am not sure if there is anything left to review if I turn this back?

Also if we pull this branch on test server, and run openml-python tests by configuring it to use v2 as done in this branch https://github.com/openml/openml-python/runs/2719068409.  it is possible to test api/v2 (which i already tried)

**Comment by sahithyaravi** [comment]
@janvanrijn  I have tried to minimize the copying of files from v1 to v2, by adding some conditions in the bootstrap function of Api_new.php. But I copied the xsd, xml templates relevant to the Api_Data file as we might make changes to these in v2 in future and I did not want to use half from v1 and half from v2 for the templates.

**Comment by sahithyaravi** [comment]
As per the meeting discussion, we plan to do minio changes in v1

**Pull request closed without merging**
